resepti_app/resepti_app/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import include, path

from resepti_app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='home'),
    path('add_resepti/', views.add_resepti, name='add_resepti'),
    path('success', views.success, name = 'success'),
    path('resepti/<int:idx>/', views.resepti, name = 'resepti'),
    path('search', views.search, name = 'search'),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('edit_resepti/<int:id>/', views.edit_resepti, name = 'edit_resepti'),
    path('poista_resepti/<int:idx>/', views.poista_resepti, name = 'poista_resepti'), 
    path('search_category/<int:cat_id>/', views.search_category, name = 'search_category'),
    path('page404', views.page404, name = 'page404'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

resepti_app/resepti_app/models.py
from django.db import models
from django.db.models.fields.related import ManyToManyField
from ckeditor.fields import RichTextField



class Category(models.Model):
    cat_name = models.CharField(max_length=200)
    
    def __str__(self):
        return self.cat_name
    
class Ingredient(models.Model):
    ing_name = models.CharField(max_length=200, unique=True)
    class Meta:
        ordering = ('ing_name',)

    def __str__(self):
        return self.ing_name

class Basic_ingredient(models.Model):
    basicing_name = models.CharField(max_length=200, blank=True, null=True)
    class Meta:
        ordering = ('basicing_name',)

    def __str__(self):
        return self.basicing_name
    

class Recipe(models.Model):
    headline = models.CharField(max_length=300)
    body_text = RichTextField(blank=True, null=True)
    image = models.ImageField(upload_to='images/')
    categoryFK = models.ForeignKey(Category, on_delete=models.CASCADE, blank=True, null=True) #SET_DEFAULT , to_field='name'
    basic_ingredient = models.ManyToManyField(Basic_ingredient, related_name='recipes', blank=True) # recipe_set

    def __str__(self):
        return f"ReseptiList: {self.id} | {self.headline}"


class Recipe_Ingredient(models.Model):
    recipe = models.ForeignKey(Recipe, on_delete=models.CASCADE, blank=True, null=True)
    ing_name = models.CharField(max_length=200)
    ingredient = models.ForeignKey(Ingredient, on_delete=models.CASCADE, blank=True, null=True)
    amount = models.CharField(max_length=50)

    class Meta:
        ordering = ('id',)

    def save(self, *args, **kwargs):
        if self.ing_name and not self.ingredient:
            (ingredient, _created) = Ingredient.objects.get_or_create(ing_name=self.ing_name)
            self.ingredient = ingredient
        super().save(*args, **kwargs)

    def __str__(self):
        return self.amount

resepti_app/resepti_app/forms.py
from django import forms
from django.db import models
from .models import Recipe, Category, Ingredient, Basic_ingredient, Recipe_Ingredient
from django.forms import ModelForm, widgets, TextInput, CheckboxInput
from ckeditor.widgets import CKEditorWidget
from ckeditor.fields import RichTextFormField


class RecipeForm(ModelForm):
    class Meta:
        model = Recipe
        fields = ['headline', 'body_text', 'image', 'categoryFK', 'basic_ingredient']
        widgets = {
            'headline': TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Lisää otsikko'
            }),
            'body_text': RichTextFormField(),
            # 'body_text': widgets.Textarea(attrs={
            #     'class': 'form-control',
            #     'placeholder': 'lisää resepti'
            # }),
            'image': widgets.FileInput(attrs={
                'class': 'form-control-file',
                'title': 'Lisää kuva'
            }),
            'categoryFK': widgets.Select(attrs={
                'class': 'form-select',
            }),
            'basic_ingredient': widgets.CheckboxSelectMultiple(attrs={
            'class': '',
            })

        }



class Basic_ingredientForm(ModelForm):
    class Meta:
        model = Basic_ingredient
        fields = ['basicing_name']
        widgets = {
            'basicing_name': widgets.CheckboxSelectMultiple(attrs={
                'class': 'form-check-input',
            }),
        }
    # def __init__(self, *args, **kwargs):
    #     super().__init__(*args, **kwargs)
    #     self.fields['basicing_name'].required = False


class IngredientForm(ModelForm):
    class Meta:
        model = Ingredient
        fields = ['ing_name']
        widgets = {
            'ing_name': TextInput(attrs={
                'class': 'form-control left',
                'placeholder': 'Lisää raaka-aine',
            }),

        }


class Recipe_IngredientForm(ModelForm):
    class Meta:
        model = Recipe_Ingredient
        fields = ['amount', 'ing_name', 'recipe']
        widgets = {
            'amount': TextInput(attrs={
                'class': 'form-control right',
                'placeholder': 'Lisää ainemäärä',
            }),
            'ing_name': TextInput(attrs={
                'class': 'form-control left',
                'placeholder': 'Lisää ainesosa',
            }),
        }


class CategoryForm(ModelForm):
    class Meta:
        model = Category
        fields = ['cat_name']
        widgets = {
            'cat_name': TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Lisää ruokalaji'
            }),
        }
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['cat_name'].required = False

resepti_app/resepti_app/views.py
import os
from django.conf import settings
from django.http import response
from django.shortcuts import render, redirect
from django.views.decorators.csrf import csrf_exempt
from django.http import JsonResponse
from django.shortcuts import HttpResponse, HttpResponseRedirect, render
from .forms import RecipeForm, CategoryForm, IngredientForm, Basic_ingredientForm, Recipe_IngredientForm
from django.core.files.storage import FileSystemStorage
from .models import Recipe, Ingredient, Category, Basic_ingredient, Recipe_Ingredient
from django.db.models import Q
from django.forms import formset_factory, modelformset_factory
from django.forms.models import inlineformset_factory
import re


def index (request):
    recipes = Recipe.objects.all()
    
    context = {
        'recipes': recipes,
    }  
    return render(request, 'resepti_app/index.html', context)

# Reseptin lisääminen funktio
def add_resepti(request):
    IngredientFormSet = modelformset_factory(Ingredient, form=IngredientForm) #modelformset_factory
    Recipe_IngredientFormSet = modelformset_factory(Recipe_Ingredient, form=Recipe_IngredientForm)
    if request.method == 'POST':
        form = RecipeForm(request.POST, request.FILES)
        cat = CategoryForm(request.POST)
        amount = Recipe_IngredientForm(request.POST)
        print('request.POST ', request.POST)
        formset = IngredientFormSet(request.POST)
        formset_amount = Recipe_IngredientFormSet(request.POST)
        print(formset_amount.cleaned_data)
        # print('REQUEST:: ', form.base_fields)
        if cat.is_valid() and cat.cleaned_data['cat_name']:
            category = cat.save()
        else:
            category = None
        
        if form.is_valid():
            if category:
                Resepti_item = form.save(commit=False)
                Resepti_item.categoryFK = category
                Resepti_item.save()
                form.save()
                print('category ', category)
            else:
                Resepti_item = form.save()
            
        if formset.is_valid() and formset_amount.is_valid():
            instance = formset.save() # Tarvitsee jos me halutaan tallentaa Recipe_Ingredientiin
            instance_amount = formset_amount.save(commit=False) # Jos poistaa commit=False, se tallentaa 2 kertaa!!!!!!!!?????
            print('SAVED')
            for form, amount in zip(instance, instance_amount):
                print('form ', form)
                print('amount', amount)
                # Tallennetaan tietokantaan kaikki Ingredienti ja Amount kentat
                ing_rec = Recipe_Ingredient(amount=amount, ingredient=form, recipe=Resepti_item, ing_name=form) # ingredient=form INSTANCE ERROR
                ing_rec.save()
                # print(ing_rec)

        # Sivun indeksi etsiminen
        item = Recipe.objects.latest('id')
        print('Last item', item.id)
        return redirect(f'/resepti/{item.id}')

    form = RecipeForm()
    form_basic_ingrediet = Basic_ingredientForm()
    form_category = CategoryForm()
    form_ingredient = IngredientForm()
    form_amount = Recipe_IngredientForm()
    formset = IngredientFormSet(request.POST or None, queryset=Ingredient.objects.none())
    formset_amount = Recipe_IngredientFormSet(request.POST or None, queryset=Recipe_Ingredient.objects.none())
    context = {
        'form': form,
        'form_basic_ingrediet': form_basic_ingrediet,
        'form_category': form_category,
        'form_ingredient': form_ingredient,
        'form_amount': form_amount,
        'formset': formset,
        'formset_amount': formset_amount,
    } 
    return render(request, 'resepti_app/add_resepti.html', context)
  
def success(request):
    return HttpResponse('successfully uploaded2')

# Saaminen tietoja tietokannasta ja laittaminen ne reseptin sivulle
def resepti(request, idx):
    recipe_ingredients = Recipe_Ingredient.objects.filter(recipe_id=idx)
    print(recipe_ingredients)
    recipe = Recipe.objects.get(id=idx)
    context = {
        'recipe': recipe,
        'recipe_ingredients': recipe_ingredients,
    }
    return render(request, 'resepti_app/resepti.html', context) 

# Etsiminen funktio
def search(request):  
    if request.method == 'GET':
        print('search_form: ', request.GET.get('search_form'))
        request_form = request.GET.get('search_form')
        items = Basic_ingredient.objects.filter(basicing_name__icontains=request_form)
        category_items = Category.objects.filter(cat_name__icontains=request_form)
        body_text_items = Recipe.objects.filter(body_text__icontains=request_form)
        headline_items = Recipe.objects.filter(headline__icontains=request_form)
        if not items.exists() and not body_text_items.exists() and not headline_items.exists() and not category_items.exists():
            recipes = None
            print('recipes ', None)
        else:
            recipes = Recipe.objects.filter(Q(basic_ingredient__in=items) | Q(body_text__icontains=request_form) | Q(headline__icontains=request_form) | Q(categoryFK__in=category_items)).distinct()
            print('recipes ', recipes)
    context = {
        'recipes': recipes,
    }
    return render(request, 'resepti_app/index.html', context)

# Kategorian etsiminen funktio
def search_category(request, cat_id):
    if request.method == 'GET':
        recipes = Recipe.objects.filter(categoryFK=cat_id)
        print('items', recipes)

        # Tarkistetaan url path, jos url /search_category/<RESEPTIN INDEX>/ palautetaan True search sivuun, ja laitetaan kategoria search kenttään
        url_ex = "^/search_category/\d+/$"
        m = re.match(url_ex, request.path)
        print('match ', m)
        url = False
        if m:
            url = True
    context = {
        'recipes': recipes,
        'url': url,
    }
    return render(request, 'resepti_app/index.html', context)

# Reseptin muokkaaminen funktio
def edit_resepti(request, id): 
    data_item = Recipe.objects.get(id=id)
    form = RecipeForm(instance=data_item)

    Recipe_IngredientFormSet = inlineformset_factory(Recipe, Recipe_Ingredient, Recipe_IngredientForm, can_delete=False, fields="__all__", extra=0)
    if request.method == 'POST':
        form = RecipeForm(request.POST, request.FILES, instance=data_item)
        formset = Recipe_IngredientFormSet(request.POST, prefix='recipe-ing', instance=data_item)
        if form.is_valid() and formset.is_valid:
            print('FORM is VALID')
            form.save()
            formset.save()
            # print('SAVED EDITING', request.POST.get("ingredient-0-ing_name"))
            print(list(request.POST.items()))
            return redirect('/resepti/' + str(id))
    else:
        formset = Recipe_IngredientFormSet(instance=data_item, prefix='recipe-ing')

    context = {
        'form': form,
        'formset': formset,
    }
    return render(request, 'resepti_app/edit_resepti.html', context)

# Poistaaminen reseptin sivu
def poista_resepti (request, idx):
    item = Recipe.objects.get(id=idx)

    recipe_ingredient_items = Recipe_Ingredient.objects.filter(recipe=item)
    for recipe_ingredient_item in recipe_ingredient_items:
        ingredient_item = Ingredient.objects.filter(id=recipe_ingredient_item.ingredient_id)
        ingredient_item.delete()
        print('ingredient_item ', ingredient_item)

    print(item.image.path)
    item.delete()
    try:
        os.remove(item.image.path)
    except:
        return redirect ('home')
    return redirect ('home')

# 404 sivu
def page404(request):
    return render(request, 'resepti_app/404.html')




# ---------------------------------------------------------------------


# def add_resepti(request):
#     if request.method == 'POST':
#         form = RecipeForm(request.POST, request.FILES)
#         cat = CategoryForm(request.POST)
#         ingredient = IngredientForm(request.POST)
#         amount = Recipe_IngredientForm(request.POST)
#         #print('REQUEST:: ', form.base_fields)
#         if cat.is_valid() and cat.cleaned_data['cat_name']:
#             category = cat.save()
#         else:
#             category = None
        
#         if form.is_valid():
#             if category:
#                 Resepti_item = form.save(commit=False)
#                 Resepti_item.categoryFK = category
#                 Resepti_item.save()
#                 form.save()
#                 print('category ', category)
#             else:
#                 Resepti_item = form.save()

#             ing = ingredient.save()
#             ing_rec = Recipe_Ingredient(amount=amount, ingredient=ing, recipe=Resepti_item)
#             ing_rec.save()
#             print(ing_rec)

#             return redirect('add_resepti')



#     form = RecipeForm()
#     form_basic_ingrediet = Basic_ingredientForm()
#     form_category = CategoryForm()
#     form_ingredient = IngredientForm()
#     form_amount = Recipe_IngredientForm()
#     context = {
#         'form': form,
#         'form_basic_ingrediet': form_basic_ingrediet,
#         'form_category': form_category,
#         'form_ingredient': form_ingredient,
#         'form_amount': form_amount,
#     }
        
#     return render(request, 'resepti_app/add_resepti.html', context)
  






# def add_resepti(request):
    
#     if request.method == 'POST':
#         form = RecipeForm(request.POST, request.FILES)
#         ing = IngredientForm(request.POST)
#         cat = CategoryForm(request.POST)
#         #print('REQUEST:: ', form.base_fields)

#         if cat.is_valid() and cat.cleaned_data['cat_name']:
#             category = cat.save()
#         else:
#             category = None

#         if ing.is_valid() and ing.cleaned_data['ing_name']:
#             ingredient = ing.save()
#         else:
#             ingredient = None
        
#         if form.is_valid():
#             if ingredient:
#                 Resepti_item = form.save(commit=False)

resepti_app/resepti_app/templates/resepti_app/add_resepti.html
{% extends "resepti_app/base.html" %}

{% load static %}

{% block title %}Lisää resepti{% endblock %}

{% block script %}
<script>
    $(document).ready(function() {
        //https://github.com/Neolot/jQuery.AutoColumnList
        //https://neolot.com/narabotki/autocolumnlist-jquery-plugin-dlya-razdeleniya-spiskov-na-kolonki
        $('#id_basic_ingredient').autocolumnlist({columns: 10});

        $('.check_warp').find("ul").addClass('list-group')
        $('.check_warp').find("li").addClass('list-group-item')
        $('.check_warp').find("input").addClass('form-check-input me-1')

        // Lisääminen raaka-aine ja ainemäärä kentätät (INPUTS) sivulle, kun painamme Lisää kentta nappi
        $('#add_field').click(function(){
            console.log('click')
            var r = /\d+/;

            // yrittämme löyttää meidän DIV ing_amount_1, jossa on inputia
            var last_div_id = $('#formset_block div:last').attr('id') //Otetaan viimeinen div:n id
            counter2 = parseInt(last_div_id.match(r), 10) + 1 // Etsimme id:ssa numero, 10 se on lukujärjestelmä ja suurentaa 1
            console.log('DIV numero ' + counter2) // Voimme katsoa Div:n numero condolissa
            var $last_div = $('#formset_block div:last').clone() // tehdään viimeinen div:n clone
            $('#formset_block div:last').after($last_div) // lisäämme uuden div vanhan div:n jälkeen
            var div_id = "ing_amount_" + counter2 // Generoidaan Div:n id counterin avulla
            $('#formset_block div:last').attr('id', div_id) //Laitetaan generoitun div:n nimi viimeseen diviin
            // Nyt meidän pitää laitaa uusi INPUT DIV:n sisään - JS kopioi DIV ja kaikki sisältö automaatisesti
            // Meidän pitää vain vaihtaa name-kentta ja id-kentta INPUT:ssa
            
            console.log('INPUT ' + $('#formset_block div:last #id_form-'+div_counter+'-ing_name').attr("name"))
            var form_name = 'form-' + counter2 + '-ing_name' // Generoidaan uuden nimen ja id
            var form_id = 'id_form-' + counter2 + '-ing_name'
            // Etsitaan edellinen INPUT siksi counter:sta vähennetaan 1, ja laitetaan uuden <name>
            var div_counter = counter2 - 1
            $('#formset_block div:last #id_form-'+div_counter+'-ing_name').attr("name", form_name) 
            $('#formset_block div:last #id_form-'+div_counter+'-ing_name').attr("id", form_id) // sama laitetaan uusi <id>

            // Nyt tehdään sama asia kuin INPUT:ssa
            var amount_form_name = 'form-' + counter2 + '-amount'
            var amount_form_id = 'id_form-' + counter2 + '-amount'
            $('#formset_block div:last #id_form-'+div_counter+'-amount').attr("name", amount_form_name)
            $('#formset_block div:last #id_form-'+div_counter+'-amount').attr("id", amount_form_id)
            
            // Lisätään yksi djanogon from laskurilla, silla tavalla Django tietää kuinka paljon meilla kentat
            $('#id_form-TOTAL_FORMS').attr('value', counter2+1) 
        })        
    })
</script>
{% endblock %}
{% block content %}
<div class="content_warp"> 
    <div class="row">
    <form method="post" class="mb-4" autocomplete="off" enctype="multipart/form-data">
        {% csrf_token %}
        {{ formset.management_form }}
        <div class="h1 pb-4 pt-4">Reseptin Lisääminen</div>
        <div class="pb-3 ">
            <p>Anna reseptille mieleisesi otsikko. Esim. "Suussasulavat suklaakeksit"</p>
            {{ form.headline }}
        </div>

        <div id="formset_block">
            <div class="mb-2 " id="ing_amount_0">
                {% if formset  %}
                {% for form_ingredient in formset %}
                    {{ form_ingredient.ing_name }}
                {% endfor %}
                {% endif %}

                {% if formset_amount  %}
                {% for el in formset_amount %}
                    {{ el.amount }}
                {% endfor %}
                {% endif %}
            </div>
        </div>

        <div style="text-align: right;" id="button">
            <a href="#" onclick="return false;" id="add_field"><button type="button" class="btn btn-success mb-4 px-4 btn_bgcolor">Lisää kenttä</button></a>
        </div>

        <div class="pb-3 border-bottom mb-4">{{ form.body_text }}</div>
        <div class="pb-3 border-bottom mb-4">
            <p class="form-headline d-flex justify-content-end">Lisää kuva</p>
            {{ form.image }}
        </div>
        
        <div class="check_warp pb-3 border-bottom mb-4">
            <p class="form-headline d-flex justify-content-end">Valitse päärakaa-aineet</p>
            <div style="display: block;">{{ form.basic_ingredient }}</div>
        </div>
        
        <div class="pb-3">
            <p class="form-headline d-flex justify-content-end">Valitse tai kirjoita ruokalaji</p>
            {{ form.categoryFK }}
        </div>
        <div class="pb-3">{{ form_category.cat_name }}</div>
        <div class="d-grid">
            <button type="submit" class="btn btn-success mb-4 px-4 btn_bgcolor">Lisää resepti</button>
        </div>
    </form>
    </div>
</div>

{% endblock %}

resepti_app/resepti_app/templates/resepti_app/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
    <script src="{% static 'resepti_app/jQuery.AutoColumnList-1.2.0/jquery.autocolumnlist.js' %}"></script>
    <!-- <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous"> -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">
    <link rel="stylesheet" type="text/css" href="{% static 'resepti_app/main.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'resepti_app/search.css' %}">
    <script type="text/javascript" src="{% static 'ckeditor/ckeditor-init.js' %}"></script>
    <script type="text/javascript" src="{% static 'ckeditor/ckeditor/ckeditor.js' %}"></script>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Outfit:wght@100;200;300;400;500;600;700;800;900&display=swap" rel="stylesheet">
    <title>{% block title %}Cook Book{% endblock %}</title>
    {% block script %}
    {% endblock %}
</head>
<body>
    <div>
        <div class="container-fluid">
            <div class="row justify-content-md-center">
                <nav class="navbar navbar-expand-sm navbar-light sticky-top" style="background-color:#ffdcbc"> <!-- #ffffef; -->
                    <div class="container-fluid ps-5">
                        <a class="navbar-brand" href="{% url 'home' %}">
                            <img src="{% static 'resepti_app/logo/rsz_1logo_transparent.png' %}" alt="logo">
                        </a>
                        <button style="padding: 0.4em; border: 0;" class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
                            <!-- <span class="navbar-toggler-icon"></span> -->
                            <img src="{% static 'resepti_app/logo/hamburger-svgrepo-com.svg' %}" alt="hamburger" style="width: 2em" />
                        </button>
                        <div class="collapse navbar-collapse" id="navbarText">
                            <ul class="navbar-nav me-auto">
                                <li class="nav-item">
                                    <a class="nav-link" href="{% url 'home' %}">Etusivu</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="{% url 'add_resepti' %}">Lisää resepti</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="{% url 'page404' %}">404 sivu</a>
                                </li>
                            </ul>
                            <span class="navbar-text"></span>
                        </div>
                    </div>
                </nav>
                {% block content %}
                {% endblock %}
            </div>
        </div>
    </div>
    <footer>
        <div class="container mt-3 mb-3" style="text-align: center;">
            <ul class="list-inline mb-3" style="font-size: 2em; color: darkred;">
                <li class="list-inline-item"><a class="link social-link rounded-circle" href="#">
                    <i class="bi bi-facebook" style="color:firebrick;"></i></a>
                </li>
                <li class="list-inline-item"><a class="link social-link rounded-circle" href="#">
                    <i class="bi bi-twitter" style="color:firebrick;"></i></a>
                </li>
                <li class="list-inline-item"><a class="link social-link rounded-circle" href="https://github.com/SergeiVasilyev/Cookbook/wiki" target="_blank">
                    <i class="bi bi-github" style="color:firebrick;"></i></a>
                </li>
            </ul>
            <p class="text-muted mb-0 small">Copyright  © Kokkikamu 2021</p>
        </div>
    </footer>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
</body>
</html>

resepti_app/resepti_app/templates/resepti_app/edit_resepti.html
{% extends "resepti_app/base.html" %}

{% load static %}

{% block title %}Muokkaa reseptiä{% endblock %}

{% block script %}
<script>
    $(document).ready(function() {
        //https://github.com/Neolot/jQuery.AutoColumnList
        //https://neolot.com/narabotki/autocolumnlist-jquery-plugin-dlya-razdeleniya-spiskov-na-kolonki
        $('#id_basic_ingredient').autocolumnlist({columns: 10});
        $('.check_warp').find("ul").addClass('list-group')
        $('.check_warp').find("li").addClass('list-group-item ')
        $('.check_warp').find("input").addClass('form-check-input me-1')
        // $('.check_warp p').click(function(){
        //     console.log($('.check_warp p').attr('class'))
        //     $('.check_warp div').toggle("slow")
        // })
    })
</script>
{% endblock %}
{% block content %}
<div class="content_warp"> 
    <div class="row">
    <form method="post" class="mb-4" autocomplete="off" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="h1 pb-4 pt-4">Reseptin Muokkaaminen</div>
        <div class="pb-3 ">
            {{ form.headline }}
        </div>
        {% if formset  %}
        {{ formset.management_form }}
        <div class="pb-3 mb-4" id="formset_block">
            {% for form in formset %}
                <div class="row">
                    <div class="col">
                        {{ form.id }}
                        {{ form.ing_name }}
                        {{ form.amount }}
                    </div>
                </div>
            {% endfor %}
        </div>
        {% endif %}
        <div class="pb-3 border-bottom mb-4">{{ form.body_text }}</div>
        <div class="pb-3 border-bottom mb-4">
            <p class="form-headline d-flex justify-content-end">Lisää kuva</p>
            {{ form.image }}
        </div>
        <div class="check_warp pb-3 border-bottom mb-4">
            <p class="form-headline d-flex justify-content-end">Valitse päärakaa-aineet</p>
            <div style="display: block;">{{ form.basic_ingredient }}</div>
        </div>
        <div class="pb-3">
            <p class="form-headline d-flex justify-content-end">Valitse tai kirjoita ruokalaji</p>
            {{ form.categoryFK }}
        </div>
        <div class="pb-3">{{ form_category.cat_name }}</div>
        <div class="d-grid gap-2">
            <button type="submit" class="btn btn-success mb-4 px-4 btn_bgcolor">Muokkaa reseptiä</button>
        </div>
    </form>
    </div>
</div>
{% endblock %}

resepti_app/resepti_app/templates/resepti_app/search.html
<div class="container">
    <div class="row height d-flex justify-content-center align-items-center">
        <div class="col">
            <div class="search">
                <form action="{% url 'search' %}" method="get">
                <input name="search_form" type="text" class="form-control" placeholder="Etsi reseptejä..." 
                    value="{% if url %}{% for el in recipes %}{% if forloop.first %}{{el.categoryFK}}{% endif %}{% endfor %}{% endif %}">
                    <button class="btn btn-primary">
                        <i class="bi bi-search"></i>
                    </button>  
                </form>
                
            </div>
        </div>
    </div>
</div>
{% comment %}  {% endcomment %}